version: '3.8'

services:
  api-prod:
    build:
      context: .
      target: production
    image: paulchapi/roomiesmart-backend:prod
    container_name: roomiesmart_api_prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${PROD_DATABASE_URL}
      - SUPABASE_URL=${PROD_SUPABASE_URL}
      - SUPABASE_KEY=${PROD_SUPABASE_KEY}