version: '3.8'

services:
  api-prod:
    image: paulchapi/roomiesmart-backend:prod
    container_name: roomiesmart_api_prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${PROD_DATABASE_URL}
      - SUPABASE_URL=${PROD_SUPABASE_URL}
      - SUPABASE_KEY=${PROD_SUPABASE_KEY}
      - KINDE_ISSUER_URL=${PROD_KINDE_ISSUER_URL}

  frontend:
    image: paulchapi/roomiesmart-frontend:prod
    container_name: roomiesmart_frontend_prod
    ports:
      - "80:80" # El puerto oficial para producción
    depends_on:
      - api-prod
    restart: always