version: '3.8'

services:
  api-dev:
    build:
      context: .
      target: development
    image: paulchapi/roomiesmart-backend:dev
    container_name: roomiesmart_api_dev
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DEV_DATABASE_URL}
      - SUPABASE_URL=${DEV_SUPABASE_URL}
      - SUPABASE_KEY=${DEV_SUPABASE_KEY}