import { supabase } from '../../../../core/database.js';
import type { IUserRepository } from '../../application/ports/user.repository.js';
import { User } from '../../domain/user.model.js';

export class SupabaseUserAdapter implements IUserRepository {
  public async save(user: User): Promise<void> {
    const { error } = await supabase
      .from('users')
      .insert({
        name: user.name,
        email: user.email,
        password_hash: user.password_hash, 
        preferences: user.preferences,     
        created_at: user.created_at.toISOString() 
      });

    if (error) {
      
      throw new Error(`Error en Supabase: ${error.message}`);
    }
  }


  public async findByEmail(email: string): Promise<User | null> {
    const { data, error } = await supabase
      .from('users')
      .select('*')
      .eq('email', email)
      .single();

    if (error || !data) return null;

    // Use the User.create factory method to ensure validation and proper instantiation
    const user = User.create(
      data.name, 
      data.email, 
      data.password_hash, 
      data.preferences
    );
    
    // If the ID is generated by Supabase, we need to set it on the user instance. Since the constructor is private, we can use a type assertion here.
    (user as any).id = data.id; 
    
    return user;
  }
}