name: Build and Deploy Backend

on:
  push:
    branches: [ "dev", "main" ] # QA removido para despliegue manual
  workflow_dispatch: # Gatillo manual para QA

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine environment tag and build target
        id: environment
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "TAG=prod" >> $GITHUB_ENV
            echo "BUILD_TARGET=production" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "qa" ]; then
            echo "TAG=qa" >> $GITHUB_ENV
            echo "BUILD_TARGET=production" >> $GITHUB_ENV
          else
            echo "TAG=dev" >> $GITHUB_ENV
            echo "BUILD_TARGET=development" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: ${{ env.BUILD_TARGET }} # Selecciona la etapa correcta del Dockerfile
          tags: paulchapi/roomiesmart-backend:${{ env.TAG }}

      # =========================================================
      # DESPLIEGUE A DESARROLLO
      # =========================================================
      - name: Deploy Backend to Dev Environment
        if: github.ref_name == 'dev'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY}}
          script: |
            cd ~/roomiesmart-backend
            docker pull paulchapi/roomiesmart-backend:dev
            docker compose -f docker-compose.dev.yml up -d --remove-orphans api

      # =========================================================
      # DESPLIEGUE A PRODUCCIÓN
      # =========================================================
      - name: Deploy Backend to Production Environment
        if: github.ref_name == 'main'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST_PROD }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/roomiesmart-production
            docker pull paulchapi/roomiesmart-backend:prod
            docker compose -f docker-compose.prod.yml up -d --remove-orphans api

      # =========================================================
      # DESPLIEGUE A QA (Manual desde GitHub)
      # =========================================================
      - name: Deploy Backend to QA Environment
        if: github.ref_name == 'qa'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST_QA }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/roomiesmart-qa
            docker pull paulchapi/roomiesmart-backend:qa
            docker compose -f docker-compose.qa.yml up -d --remove-orphans api